### ISSUE TITLE
Описание запуска приложения

### ISSUE THREAD

**Issue by abataloff** [ManyakRus/image_packages#2]
https://github.com/ManyakRus/image_packages/blob/efc70e8682939663f975944a2efd9270cd00462a/README.md?plain=1#L26C1-L26C48

Сейчас данный кусок документации выглядит как
_| image_packages <filename.graphml>_
хотя в исходниках документации написано
_>image_packages <your repository directory> <filename.graphml>_

Путает пользователя

**Comment by abataloff** [comment]
Я к тому что у команды image_packages два аргумента  _your repository directory_ и _filename.graphml_
А github рендерит в строку image_packages _filename.graphml_, тем самым удаляет первый аргумент _your repository directory_ Или все же один аргумент у команды?

**Comment by ManyakRus** [comment]
исправил.
Это github неправильно отображает правильный текст
